export const colors=[
    {
        name:'Primary',
        value:"#174ae7"
    },
    {
        name:'Secondary',
        value:"#6c757d"
    }
];

export const buttons=[
    {
        type:'Primary',
        attributes:{
            border:"none",
            padding:"10px",
            fontSize:"14px",
            fontFamily:"Arial",
            fontWeight:'normal',
            textDecoration:'none',
            fontStyle:'normal',
            color:'#ffffff',
            backgroundColor:'#174ae7',
            themeBackgroundColor:'Primary',
            borderRadius:'0px',
            minWidth:'80px'
        }
    },
    {
        type:'Secondary',
        attributes:{
            border:"none",
            padding:"10px",
            fontSize:"14px",
            fontFamily:"Arial",
            fontWeight:'normal',
            textDecoration:'none',
            fontStyle:'normal',
            color:'#ffffff',
            backgroundColor:'#6c757d',
            themeBackgroundColor:'Secondary',
            borderRadius:'0px',
            minWidth:'80px'
        }
    }
]

export const image={
        type:'image',
        attributes:{
            borderRadius:'0%',
            borderWidth:'0px',
            borderStyle:'solid',
            borderColor:'#000000'
        }
}


export const background={
    backgroundColor:'#ffffff',
    pages:[]
}


export const fonts=[
    {
        type:'DFLT',
        attributes:{
            fontSize:"12px",
            fontFamily:"Arial",
            fontWeight:'normal',
            textDecoration:'none',
            fontStyle:'normal',
            color:'#000000',
        }
    },
    {
        type:'PAR',
        attributes:{
            fontSize:"15px",
            fontFamily:"Arial",
            fontWeight:'normal',
            textDecoration:'none',
            fontStyle:'normal',
            color:'#000000',
        }
    },
    {
        type:'H1',
        attributes:{
            fontSize:"34px",
            fontFamily:"Arial",
            fontWeight:'normal',
            textDecoration:'none',
            fontStyle:'normal',
            color:'#000000',
        }
    },
    {
        type:'H2',
        attributes:{
            fontSize:"30px",
            fontFamily:"Arial",
            fontWeight:'normal',
            textDecoration:'none',
            fontStyle:'normal',
            color:'#000000',
        }
    },
    {
        type:'H3',
        attributes:{
            fontSize:"24px",
            fontFamily:"Arial",
            fontWeight:'normal',
            textDecoration:'none',
            fontStyle:'normal',
            color:'#000000',
        }
    },
    {
        type:'H4',
        attributes:{
            fontSize:"20px",
            fontFamily:"Arial",
            fontWeight:'normal',
            textDecoration:'none',
            fontStyle:'normal',
            color:'#000000',
        }
    },
    {
        type:'H5',
        attributes:{
            fontSize:"18px",
            fontFamily:"Arial",
            fontWeight:'normal',
            textDecoration:'none',
            fontStyle:'normal',
            color:'#000000',
        }
    },
    {
        type:'H6',
        attributes:{
            fontSize:"16px",
            fontFamily:"Arial",
            fontWeight:'normal',
            textDecoration:'none',
            fontStyle:'normal',
            color:'#000000',
        }
    }
]

export const property={
    "backgroundColor":"background-color",
    "border":"border",
    "borderColor":"border-color",
    "borderWidth":"border-width",
    "borderRadius":"border-radius",
    "borderTopLeftRadius":"border-top-left-radius",
    "borderTopRightRadius":"border-top-right-radius",
    "borderBottomLeftRadius":"border-bottom-left-radius",
    "borderBottomRightRadius":"border-bottom-right-radius",
    "borderTopStyle":"border-top-style",
    "borderLeftStyle":"border-left-style",
    "borderRightStyle":"border-right-style",
    "borderBottomStyle":"border-bottom-style",
    "color":"color",
    "fontFamily":"font-family",
    "fontSize":"font-size",
    "fontStyle":"font-style",
    "fontWeight":"font-weight",
    "minWidth":"min-width",
    "padding":"padding",
    "textDecoration":"text-decoration",
    "themeColor":"theme-color",
    "themeBackgroundColor":"theme-background-color"
}