const defaultElements = [
  {
    elementTitle: "Journal",
    elementParent: "tasksAndGoals",
    id: "tasksAndGoals/journal",
    navLink: "/tasksAndGoals",
  },
  {
    elementTitle: "Appointment",
    elementParent: "calendar",
    id: "calendar/appointment",
    navLink: "/calendar",
  },
  {
    elementTitle: "Templates",
    elementParent: null,
    id: "documents/templates",
    navLink: "/documents",
  },
  {
    elementTitle: "Emails",
    elementParent: "marketing",
    id: "marketing/email",
    navLink: "/marketing",
  },
  {
    elementTitle: "Tickets",
    elementParent: "marketing",
    id: "marketing/ticket",
    navLink: "/marketing",
  },
  {
    elementTitle: "Membership",
    elementParent: "shop",
    id: "shop/membership",
    navLink: "/ecommerce/shop",
  },
  {
    elementTitle: "Courses",
    elementParent: "shop",
    id: "shop/courses",
    navLink: "/ecommerce/shop",
  },
  {
    elementTitle: "Income",
    elementParent: "finance",
    id: "finance/income",
    navLink: "/finance",
  },
  {
    elementTitle: "Attendance",
    elementParent: "calendar",
    id: "calendar/attendance",
    navLink: "/calendar",
  },
  {
    elementTitle: "Chat",
    elementParent: "marketing",
    id: "marketing/chat",
    navLink: "/marketing",
  },
  {
    elementTitle: "Expired",
    elementParent: "statistics",
    id: "statistics/expired",
    navLink: "/business/statistics",
  },
  {
    elementTitle: "Shop",
    elementParent: null,
    id: "shop",
    navLink: "/ecommerce/shop",
  },
  {
    elementTitle: "Settings",
    elementParent: null,
    id: "settings",
    navLink: "/setting",
  },
  {
    elementTitle: "Advance Settings",
    elementParent: "settings",
    id: "settings/advance",
    navLink: "/setting",
  },
  {
    elementTitle: "Tasks & Goals",
    elementParent: null,
    id: "tasksAndGoals",
    navLink: "/tasksAndGoals",
  },
  {
    elementTitle: "Tasks",
    elementParent: "tasksAndGoals",
    id: "tasksAndGoals/tasks",
    navLink: "/tasksAndGoals",
  },
  {
    elementTitle: "Marketing",
    elementParent: null,
    id: "marketing",
    navLink: "/marketing",
  },
  {
    elementTitle: "Social Contact",
    elementParent: "mysocial",
    id: "mysocial/socialContact",
    navLink: "/mysocial",
  },
  {
    elementTitle: "Social Proof",
    elementParent: "mysocial",
    id: "mysocial/socialProof",
    navLink: "/mysocial",
  },
  {
    elementTitle: "Coupons",
    elementParent: "shop",
    id: "shop/coupons",
    navLink: "/ecommerce/shop",
  },
  
  {
    elementTitle: "Calendar",
    elementParent: null,
    id: "calendar",
    navLink: "/calendar",
  },
  {
    elementTitle: "Statistics",
    elementParent: null,
    id: "statistics",
    navLink: "/business/statistics",
  },
  {
    elementTitle: "Dashboard",
    elementParent: 'statistics',
    id: "statistics/dashboard",
    navLink: "/business/statistics",
  },
  {
    elementTitle: "Products",
    elementParent: "shop",
    id: "shop/products",
    navLink: "/ecommerce/shop",
  },
  {
    elementTitle: "Invoice",
    elementParent: "finance",
    id: "finance/invoice",
    navLink: "/finance",
  },
  {
    elementTitle: "File Manager",
    elementParent: null,
    id: "file-manager",
    navLink: "/filemanager",
  },
  {
    elementTitle: "Notifications",
    elementParent: "settings",
    id: "settings/notifications",
    navLink: "/setting",
  },
  
  {
    elementTitle: "QR Barcode",
    elementParent: "business",
    id: "business/qrBarcode",
    navLink: "/business/tools",
  },
  {
    elementTitle: "Statistics",
    elementParent: null,
    id: "statistics",
    navLink: "/business/statistics",
  },
  {
    elementTitle: "Retention",
    elementParent: "statistics",
    id: "statistics/retention",
    navLink: "/business/statistics",
  },
  {
    elementTitle: "Expenses",
    elementParent: "finance",
    id: "finance/expenses",
    navLink: "/finance",
  },
  {
    elementTitle: "Profit & Loss",
    elementParent: "finance",
    id: "finance/profitloss",
    navLink: "/finance",
  },
  {
    elementTitle: "Permissions & Roles",
    elementParent: "settings",
    id: "settings/permissions",
    navLink: "/setting",
  },
  {
    elementTitle: "Dashboard",
    elementParent: null,
    id: "dashboard",
    navLink: "/dashboard/analytics",
  },
  {
    elementTitle: "Goals",
    elementParent: "tasksAndGoals",
    id: "tasksAndGoals/goals",
    navLink: "/tasksAndGoals",
  },
  {
    elementTitle: "Reporting",
    elementParent: "tasksAndGoals",
    id: "tasksAndGoals/reporting",
    navLink: "/tasksAndGoals",
  },
  {
    elementTitle: "Documents",
    elementParent: null,
    id: "documents",
    navLink: "/documents",
  },
  {
    elementTitle: "Business Tools",
    elementParent: null,
    id: "business",
    navLink: "/business/tools",
  },
  {
    elementTitle: "Finance",
    elementParent: null,
    id: "finance",
    navLink: "/finance",
  },
  {
    elementTitle: "Security",
    elementParent: "settings",
    id: "settings/security",
    navLink: "/setting",
  },
  {
    elementTitle: "My Social",
    elementParent: null,
    id: "mysocial",
    navLink: "/mysocial",
  },
  {
    elementTitle: "Reputation",
    elementParent: "mysocial",
    id: "mysocial/reputation",
    navLink: "/mysocial",
  },
  {
    elementTitle: "Progression",
    elementParent: "statistics",
    id: "statistics/progression",
    navLink: "/business/statistics",
  },
  {
    elementTitle: "Account",
    elementParent: "settings",
    id: "settings/account",
    navLink: "/setting",
  },
  {
    elementTitle: "Deposit",
    elementParent: "settings",
    id: "settings/deposit",
    navLink: "/setting",
  },
  {
    elementTitle: "Organizations",
    elementParent: null,
    id: "organizations",
    navLink: "/organizations/",
  },
  {
    elementTitle: "Contacts",
    elementParent: null,
    id: "contacts",
    navLink: "/contacts/",
  },
  {
    elementTitle: "Events",
    elementParent: "calendar",
    id: "calendar/event",
    navLink: "/calendar",
  },
  {
    elementTitle: "Booking",
    elementParent: "calendar",
    id: "calendar/booking",
    navLink: "/calendar",
  },
  {
    elementTitle: "Text",
    elementParent: "marketing",
    id: "marketing/text",
    navLink: "/marketing",
  },
  {
    elementTitle: "Automation",
    elementParent: "marketing",
    id: "marketing/automation",
    navLink: "/marketing",
  },
  {
    elementTitle: "Project Manager",
    elementParent: "business",
    id: "business/projectManager",
    navLink: "/business/tools",
  },
  {
    elementTitle: "Forms & Funnels",
    elementParent: "business",
    id: "business/formsFunnels",
    navLink: "/business/tools",
  },
  {
    elementTitle: "Birthday",
    elementParent: "statistics",
    id: "statistics/birthday",
    navLink: "/business/statistics",
  },
  {
    elementTitle: "Billing",
    elementParent: "settings",
    id: "settings/billing",
    navLink: "/setting",
  },
  {
    elementTitle: "Progression",
    elementParent: "settings",
    id: "settings/progression",
    navLink: "/setting",
  },
];

const contactElements = [
  {
    elementTitle: "Journal",
    elementParent: "tasksAndGoals",
    id: "tasksAndGoals/journal",
    navLink: "/tasksAndGoals",
  },
  {
    elementTitle: "Dashboard",
    elementParent: null,
    id: "dashboard",
    navLink: "/dashboard/analytics",
  },
  {
    elementTitle: "Tasks & Goals",
    elementParent: null,
    id: "tasksAndGoals",
    navLink: "/tasksAndGoals",
  },
  {
    elementTitle: "Shop",
    elementParent: null,
    id: "shop",
    navLink: "/ecommerce/shop",
  },
  {
    elementTitle: "Tasks",
    elementParent: "tasksAndGoals",
    id: "tasksAndGoals/tasks",
    navLink: "/tasksAndGoals",
  },
  {
    elementTitle: "File Manager",
    elementParent: null,
    id: "file-manager",
    navLink: "/filemanager",
  },
  {
    elementTitle: "Goals",
    elementParent: "tasksAndGoals",
    id: "tasksAndGoals/goals",
    navLink: "/tasksAndGoals",
  },
  {
    elementTitle: "Documents",
    elementParent: null,
    id: "documents",
    navLink: "/documents",
  },
];
module.exports = { defaultElements , contactElements };
